[workspace]
members = [
    "aoc20*/day*",
    "aoc-macro",
    "cli-runner",
    "common",
    "utils",
]

[workspace.package]
version = "0.1.0"
authors = ["Philippe Cholet"]
repository = "https://github.com/Philippe-Cholet/rusty-aoc"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
# Common dependencies to my solvers
anyhow = "1.0.71"
good_lp = { version = "1.4.0", features = ["lp-solvers"], default-features = false }
itertools = "0.11.0"
md5 = "0.7.0"
ndarray = "0.15.6"
pest = "2.7.0"
pest_derive = "2.7.0"
petgraph = "0.6.3"
serde_json = "1.0.100"
# Dependencies to create procedural macros
cargo_toml = "0.15.3"
quote = "1.0.29"
syn = "2.0.25"

[profile.final]
inherits = "release"
lto = true
codegen-units = 1
panic = 'abort'

[profile.flamegraph]
inherits = "final"
debug = true
