[workspace]
members = [
    "aoc20*/day*",
    "aoc-macro",
    "cli-runner",
    "common",
    "utils",
]

[workspace.package]
version = "0.1.0"
authors = ["Philippe Cholet"]
repository = "https://github.com/Philippe-Cholet/rusty-aoc"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
# Common dependencies to my solvers
anyhow = "1.0.68"
good_lp = { version = "1.3.2", features = ["lp-solvers"], default-features = false }
itertools = "0.11.0"
md5 = "0.7.0"
ndarray = "0.15.6"
pest = "2.5.5"
pest_derive = "2.5.5"
petgraph = "0.6.2"
serde_json = "1.0.93"
# Dependencies to create procedural macros
cargo_toml = "0.14.0"
quote = "1.0.23"
syn = "1.0.107"
