[workspace]
members = [
    "aoc20*/day*",
    "aoc-macro",
    "cli-runner",
    "common",
    "utils",
    "web",
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.74"
version = "0.1.0"
authors = ["Philippe Cholet"]
repository = "https://github.com/Philippe-Cholet/rusty-aoc"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
# Common dependencies to my solvers
anyhow = "1.0.75"
good_lp = { version = "1.7.0", features = ["lp-solvers"], default-features = false }
itertools = "0.12.0"
md5 = "0.7.0"
memchr = "2.6.4"
ndarray = "0.15.6"
permutohedron = "0.2.4"
pest = "2.7.5"
pest_derive = "2.7.5"
petgraph = "0.6.4"
rustc-hash = "1.1.0"
serde_json = "1.0.108"
# Dependencies to create procedural macros
cargo_toml = "0.17.1"
quote = "1.0.33"
syn = "2.0.39"
clap = { version = "4.4.10", features = ["derive"] }
thiserror = "1.0.50"
ureq = "2.9.1"
webbrowser = "0.8.12"

[profile.final]
inherits = "release"
lto = true
codegen-units = 1
panic = 'abort'

[profile.flamegraph]
inherits = "final"
debug = true
