[package]
name = "aoc22-19"
edition = "2021"
description = "My solution for the Advent of Code 2022 day 19"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lib]
doctest = false

[dependencies]
good_lp = { version = "1.3.2", features = ["lp-solvers"], default-features = false }
common = { path="../../common" }
utils = { path="../../utils" }
