[package]
name = "aoc21-17"
edition = "2021"
description = "My solution for the Advent of Code 2021 day 17"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lib]
doctest = false

[dependencies]
itertools.workspace = true
common = { path="../../common" }
