[alias]
f = "fmt --check"
clip = "clippy -- -W clippy::all -W clippy::pedantic -W clippy::nursery -W clippy::unwrap_used -W clippy::expect_used -A clippy::missing-errors-doc"
cli = "run --bin cli-runner"

[env]
# RUST_BACKTRACE="1"
