[alias]
rr = "run --release"

tr = "test --release"
tri = "tr -- --ignored"
trii = "tr -- --include-ignored"

nt = "nextest run"
nti = "nt --run-ignored ignored-only"
ntii = "nt --run-ignored all"

ntr = "nextest run -r"
ntri = "ntr --run-ignored ignored-only"
ntrii = "ntr --run-ignored all"

f = "fmt --check"

clip = "clippy -- -W clippy::all -W clippy::pedantic -W clippy::nursery -W clippy::unwrap_used -W clippy::expect_used -W clippy::disallowed-types -A clippy::missing-errors-doc"

cli = "run --bin cli-runner --profile final"

flame = "flamegraph --profile flamegraph"

[env]
# RUST_BACKTRACE="1"
