[package]
name = "aoc21-21"
edition = "2021"
description = "My solution for the Advent of Code 2021 day 21"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
itertools.workspace = true
common = { path="../../common" }
