[package]
name = "utils"
edition = "2021"
description = "Utilities that my solutions can all use for Advents of Code"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lib]
doctest = false

[dependencies]
common = { path="../common" }
